config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "sentences#index"

  resources :sentences, only: [:show, :index] do
    resources :entities, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :sentence

  validates :text, :typ, presence: true
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  has_many :entities, dependent: :destroy

  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def create
    sentence_id = params.require(:sentence_id)
    text = params[:text]
    typ = params[:typ]
    Entity.create!(sentence_id: sentence_id, text: text, typ: typ)
    redirect_to request.referer
  end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  def index
    @sentences = Sentence.all
  end

  def show
    id = params.require(:id)
    @sentence = Sentence.includes(:entities).find(id)
  end
  
  def create_entity
    sentence_id = params.require(:sentence_id)
    text = params[:text]
    typ = params[:typ]
    Entity.create!(sentence_id: sentence_id, text: text, typ: typ)
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mitre</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sentences/index.html.erb
<h1>Sentences</h1>
<ol>
  <% @sentences.each do |sentence| %>
    <li><%= link_to sentence.text, sentence %></li>
  <% end %>
</ol>

app/views/sentences/show.html.erb
<% sentence = SentencePresenter.new(@sentence) %>

<div class="sentence">
<% sentence.chunks.each do |chunk| %>
  <% if chunk.typ %>
    <div class="entity" style="background: <%= chunk.color %>">
      <span class="entityText"><%= chunk.text %></span>
      <span class="entityType"><%= chunk.typ %></span>
    </div>
  <% elsif chunk.selectable %>
    <div class="entity selectable">
      <%= chunk.text -%>
      <br><br>
      <div class="addEntity"> 
        <%= form_with url: sentence_entities_path(@sentence), method: :post do |form| %>
          <%= form.hidden_field :text, :value => chunk.text %>
          <%= form.text_field :typ, :value => "TYPE" %>
          <%= form.submit "Tag It" %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="entity">
      <%= chunk.text -%>
    </div>
  <% end %>
<% end %>
</div>